name: CI - Clean and Train data
on: workflow_dispatch

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - run: |
          echo ${{ github.workspace }}
          echo $GITHUB_WORKSPACE
      - name: clean_data
        run: |
          pwd
          ls -al
          pip install -r src/requirements.txt
          python src/clean_data.py
      - name: train_model
        run: |
          pwd
          ls -al
          pip install -r src/requirements.txt
          python src/train.py
